/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.AlunoControl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class GerenciarAluno extends javax.swing.JFrame {

    private AlunoControl control;

    /**
     * Creates new form GerenciarAluno
     */
    public GerenciarAluno() {
        initComponents();
        this.control = new AlunoControl();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_nome = new javax.swing.JLabel();
        textField_nome = new java.awt.TextField();
        jLabel_idade = new javax.swing.JLabel();
        textField_idade = new java.awt.TextField();
        jLabel_curso = new javax.swing.JLabel();
        textField_curso = new java.awt.TextField();
        jLabel_fase = new javax.swing.JLabel();
        textField_fase = new java.awt.TextField();
        jButton_cancelar = new javax.swing.JButton();
        jButton_alterar = new javax.swing.JButton();
        jButton_apagar = new javax.swing.JButton();

        setTitle("Tela de Gerenciamento");
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Curso", "Fase"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 180));

        jLabel_nome.setText("Nome:");
        jPanel2.add(jLabel_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 229, -1, -1));

        textField_nome.setText("");
        jPanel2.add(textField_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 229, 192, -1));

        jLabel_idade.setText("Idade:");
        jPanel2.add(jLabel_idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 267, -1, -1));

        textField_idade.setText("");
        jPanel2.add(textField_idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 267, 81, -1));

        jLabel_curso.setText("Curso:");
        jPanel2.add(jLabel_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 305, -1, -1));

        textField_curso.setText("");
        jPanel2.add(textField_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 305, 192, -1));

        jLabel_fase.setText("Fase:");
        jPanel2.add(jLabel_fase, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 343, -1, -1));

        textField_fase.setText("");
        jPanel2.add(textField_fase, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 343, 79, -1));

        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 393, -1, -1));

        jButton_alterar.setText("Alterar");
        jButton_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 393, 80, -1));

        jButton_apagar.setText("Apagar");
        jButton_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_apagarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 393, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (this.jTable1.getSelectedRow() != -1) { //coluna -1 --> aparentemente é fora // coluna 0 --> id
            String nome = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1).toString(); //getValueAt --> retorna o valor inserido na linha,coluna
            String idade = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 2).toString();
            String curso = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 3).toString();
            String fase = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 4).toString();

            this.textField_nome.setText(nome);
            this.textField_idade.setText(idade);
            this.textField_curso.setText(curso);
            this.textField_fase.setText(fase);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterarActionPerformed
        // TODO add your handling code here:

        try {
            //Tratamento para caso de algum dado vazio + try catch para tratar erros            
            if (this.textField_nome.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Nome não pode ser vazio!");
            } else if (this.textField_idade.getText().length() < 2) {
                JOptionPane.showMessageDialog(null, "Idade deve conter ao menos 2 caracteres!");
            } else if (this.textField_curso.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Curso não pode ser vazio!");
            } else if (this.textField_fase.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Fase não pode ser vazio!");
            } else {

                int id = Integer.parseInt(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0).toString());
                String nome = this.textField_nome.getText();
                int idade = Integer.parseInt(this.textField_idade.getText());
                String curso = this.textField_curso.getText();
                int fase = Integer.parseInt(this.textField_fase.getText());

                if (control.editarAluno(curso, fase, id, nome, idade)) {
                    JOptionPane.showMessageDialog(null, "Aluno alterado com sucesso!");

                    //Limpa os dados
                    this.textField_nome.setText("");
                    this.textField_idade.setText("");
                    this.textField_curso.setText("");
                    this.textField_fase.setText("");
                    System.out.println(control.getListaAlunos().toString());
                    carregarTabela();
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Erro!\nVerifique os dados inseridos e tente novamente");
                }

            }
        } catch (NumberFormatException a) {
            JOptionPane.showMessageDialog(null, "Verifique os dados inseridos novamente");
        } catch (ArrayIndexOutOfBoundsException b) {
            JOptionPane.showMessageDialog(null, "Primeiro deve-se cadastrar ou selecionar na tabela algum Aluno para então edita-lo");
        }

    }//GEN-LAST:event_jButton_alterarActionPerformed

    private void jButton_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_apagarActionPerformed
        // TODO add your handling code here:
        try {

            //Tratamento para caso de algum dado vazio + try catch para tratar erros            
            if (this.textField_nome.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Nome não pode ser vazio!");
            } else if (this.textField_idade.getText().length() < 2) {
                JOptionPane.showMessageDialog(null, "Idade deve conter ao menos 2 caracteres!");
            } else if (this.textField_curso.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Curso não pode ser vazio!");
            } else if (this.textField_fase.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Fase não pode ser vazio!");
            } else {

                int id = Integer.parseInt(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0).toString());
                String nome = this.textField_nome.getText();
                int idade = Integer.parseInt(this.textField_idade.getText());
                String curso = this.textField_curso.getText();
                int fase = Integer.parseInt(this.textField_fase.getText());

                if (control.deletarAluno(id)) {
                    JOptionPane.showMessageDialog(null, "Aluno Apagado com sucesso!");

                    //Limpa os dados
                    this.textField_nome.setText("");
                    this.textField_idade.setText("");
                    this.textField_curso.setText("");
                    this.textField_fase.setText("");
                    System.out.println(control.getListaAlunos().toString());
                    carregarTabela();
                    
                }else {
                    JOptionPane.showMessageDialog(null, "Erro!\nVerifique os dados inseridos e tente novamente");
                }

            }

        } catch (NumberFormatException a) {
            JOptionPane.showMessageDialog(null, "Verifique os dados inseridos novamente");
        } catch (ArrayIndexOutOfBoundsException b) {
            JOptionPane.showMessageDialog(null, "Primeiro deve-se cadastrar ou selecionar na tabela algum Aluno para então apaga-lo");
        }

    }//GEN-LAST:event_jButton_apagarActionPerformed

    public void carregarTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        modelo.setNumRows(0);

        String[][] tabela = control.listaTabela();

        for (int i = 0; i < tabela.length; i++) {
            modelo.addRow(new Object[]{
                tabela[i][0],
                tabela[i][1],
                tabela[i][2],
                tabela[i][3],
                tabela[i][4],});
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_alterar;
    private javax.swing.JButton jButton_apagar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JLabel jLabel_curso;
    private javax.swing.JLabel jLabel_fase;
    private javax.swing.JLabel jLabel_idade;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextField textField_curso;
    private java.awt.TextField textField_fase;
    private java.awt.TextField textField_idade;
    private java.awt.TextField textField_nome;
    // End of variables declaration//GEN-END:variables
}
